#!/bin/bash

old="$(cat "/sys/class/backlight/intel_backlight/brightness")"
max="$(cat "/sys/class/backlight/intel_backlight/max_brightness")"

new=$(($old-20))

sudo sh -c "echo $new > /sys/class/backlight/intel_backlight/brightness"
